#!/bin/bash

# ECHO COMMAND
echo Hello World!

# VARIABLES
# Uppercase by convention
# Letters, Numbers, Underscores

NAME="Ayden"
echo "My name is $NAME"
# echo "My name is ${NAME}"

# USER INPUT
read -p "Enter your name: " NAME
echo "Hello $NAME, nice to meet you"

# SIMPLE IF STATEMENT
if [ "$NAME" == "Ayden" ]
then
    echo "Your name is Ayden"
else
    echo "Your name is NOT Ayden"
fi

# COMPARISON
NUM1=3
NUM2=5
if [ "$NUM1" -gt "$NUM2" ]
then
    echo "$NUM1 if greater than $NUM2"
else
    echo "$NUM1 is less than $NUM2"
fi


#########
# val1 -eq val2 -> Returns if the values are equal
# val1 -ne val2 -> Returns true if the values are not equal
# val1 -gt val2 -> Returns true if val1 is greater than val2
# val1 -ge val2 -> Returns true if val1 is greater or equal to val2
# val1 -lt val2 -> Returns true if val1 is less than val2
# val1 -le val2 -> Returns true if val1 is less than or equal to val2
#########

# FILE CONDITIONS
